/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera, useAnimations } from "@react-three/drei";

const SplineTestModel = ({ ...props }) => {
    const { nodes, materials, animations } = useSpline(
        "https://prod.spline.design/QiiAuQqB3xo5lqII/scene.splinecode"
    );
    const { ref, actions, names } = useAnimations(animations)
    console.log(ref, actions, names)
    return (
        <>
            <color attach="background" args={["#f5c9da"]} />
            <group scale={0.5} {...props} dispose={null}>
                <scene name="Scene">
                    <mesh
                        name="Backdrop"
                        geometry={nodes.Backdrop.geometry}
                        material={materials["Backdrop Material"]}
                        castShadow
                        receiveShadow
                        position={[-74.5, 652.5, 2514.2]}
                    />
                    <directionalLight
                        name="Directional Light"
                        castShadow
                        intensity={0.7}
                        shadow-mapSize-width={2048}
                        shadow-mapSize-height={2048}
                        shadow-camera-near={-10000}
                        shadow-camera-far={100000}
                        shadow-camera-left={-1250}
                        shadow-camera-right={1250}
                        shadow-camera-top={1250}
                        shadow-camera-bottom={-1250}
                        position={[200.36, 353.45, 300]}
                    />
                    <group
                        name="coffee"
                        position={[-153.71, -59.99, 306.08]}
                        rotation={[0.15, -0.04, -0.27]}
                        scale={0.86}
                    >
                        <mesh
                            name="Cylinder 4"
                            geometry={nodes["Cylinder 4"].geometry}
                            material={materials["color-5"]}
                            castShadow
                            receiveShadow
                            position={[-14.56, 41.51, 5.45]}
                            rotation={[0.26, 0.02, 0.08]}
                            scale={1}
                        />
                        <mesh
                            name="Cylinder 3"
                            geometry={nodes["Cylinder 3"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[0, 18.91, 0]}
                            scale={1}
                        />
                        <mesh
                            name="Cylinder 2"
                            geometry={nodes["Cylinder 2"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-0.39, -30.22, -1.03]}
                            scale={1}
                        />
                        <mesh
                            name="Cylinder"
                            geometry={nodes.Cylinder.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[-0.39, -37.79, -1.03]}
                            scale={1}
                        />
                    </group>
                    <group
                        name="Lifebuoy"
                        position={[368.86, -246.68, -203.91]}
                        rotation={[-0.15, -0.44, -0.77]}
                        scale={0.9}
                    >
                        <mesh
                            name="Torus 8"
                            geometry={nodes["Torus 8"].geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0, 0, 0]}
                            rotation={[0, 0, -0.26]}
                            scale={1}
                        />
                        <mesh
                            name="Torus 6"
                            geometry={nodes["Torus 6"].geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0, 0, 0]}
                            rotation={[0, 0, -1.83]}
                            scale={1}
                        />
                        <mesh
                            name="Torus 4"
                            geometry={nodes["Torus 4"].geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0, 0, 0]}
                            rotation={[0, 0, 2.88]}
                            scale={1}
                        />
                        <mesh
                            name="Torus 2"
                            geometry={nodes["Torus 2"].geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0, 0, 0]}
                            rotation={[0, 0, 1.31]}
                            scale={1}
                        />
                        <mesh
                            name="Torus 7"
                            geometry={nodes["Torus 7"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[0, 0, 0]}
                            rotation={[0, 0, -Math.PI / 3]}
                            scale={1}
                        />
                        <mesh
                            name="Torus 5"
                            geometry={nodes["Torus 5"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[0, 0, 0]}
                            rotation={[0, 0, -2.62]}
                            scale={1}
                        />
                        <mesh
                            name="Torus 3"
                            geometry={nodes["Torus 3"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[0, 0, 0]}
                            rotation={[0, 0, 2.09]}
                            scale={1}
                        />
                        <mesh
                            name="Torus"
                            geometry={nodes.Torus.geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[0, 0, 0]}
                            rotation={[0, 0, Math.PI / 6]}
                            scale={1}
                        />
                    </group>
                    <group
                        name="beaker"
                        position={[-422.26, 12.06, 41.74]}
                        rotation={[0.69, 0.28, 0.49]}
                        scale={0.84}
                    >
                        <mesh
                            name="Cylinder1"
                            geometry={nodes.Cylinder1.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0.64, -45.33, 0.71]}
                            scale={1}
                        />
                        <mesh
                            name="Cube"
                            geometry={nodes.Cube.geometry}
                            material={materials["Cube Material"]}
                            castShadow
                            receiveShadow
                            position={[0, -13.67, 0]}
                        />
                    </group>
                    <group
                        name="card"
                        position={[-275.5, -150, 329.71]}
                        rotation={[-0.41, -0.22, -0.22]}
                        scale={0.78}
                    >
                        <mesh
                            name="Rectangle 7"
                            geometry={nodes["Rectangle 7"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-39.24, 0.91, 0.48]}
                        />
                        <mesh
                            name="Rectangle 8"
                            geometry={nodes["Rectangle 8"].geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[-39.24, 10.75, 2.07]}
                            rotation={[0, 0, -Math.PI / 2]}
                            scale={1}
                        />
                        <mesh
                            name="Rectangle 6"
                            geometry={nodes["Rectangle 6"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-39.24, 11.05, 0.48]}
                        />
                        <mesh
                            name="Rectangle 5"
                            geometry={nodes["Rectangle 5"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-39.24, 21.5, 0.48]}
                        />
                        <mesh
                            name="Rectangle 4"
                            geometry={nodes["Rectangle 4"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-57.89, -24.25, 0.48]}
                        />
                        <mesh
                            name="Rectangle 3"
                            geometry={nodes["Rectangle 3"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-32.79, -36.18, 0.48]}
                        />
                        <mesh
                            name="Ellipse 2"
                            geometry={nodes["Ellipse 2"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[47.39, -27.44, 0.49]}
                        />
                        <mesh
                            name="Ellipse"
                            geometry={nodes.Ellipse.geometry}
                            material={materials["color-5"]}
                            castShadow
                            receiveShadow
                            position={[27.75, -27.44, 0.49]}
                        />
                        <mesh
                            name="Rectangle 2"
                            geometry={nodes["Rectangle 2"].geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0, 0, -6.07]}
                        />
                    </group>
                    <group
                        name="trophy"
                        position={[-381.16, 221.26, -331.52]}
                        rotation={[-0.09, -0.13, 0.44]}
                        scale={[1.93, 1.85, 1.9]}
                    >
                        <mesh
                            name="Cylinder 21"
                            geometry={nodes["Cylinder 21"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[0.71, 35.73, 40.73]}
                            rotation={[1.92, 0, 0]}
                            scale={1}
                        />
                        <mesh
                            name="Star"
                            geometry={nodes.Star.geometry}
                            material={materials["color-5"]}
                            castShadow
                            receiveShadow
                            position={[0.6, 36.02, 37.55]}
                            rotation={[0.35, 0, 0]}
                            scale={1}
                        />
                        <mesh
                            name="Cylinder2"
                            geometry={nodes.Cylinder2.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[-0.19, -68.82, 0.2]}
                            rotation={[Math.PI, 0, 0]}
                        />
                        <mesh
                            name="Cube 3"
                            geometry={nodes["Cube 3"].geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[-59.18, 25.54, -1.28]}
                            rotation={[0, 0, Math.PI / 6]}
                            scale={[-1, 1, 1]}
                        />
                        <mesh
                            name="Cube 2"
                            geometry={nodes["Cube 2"].geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[59.18, 26.26, -1.28]}
                            rotation={[0, 0, -Math.PI / 6]}
                            scale={1}
                        />
                        <mesh
                            name="Cube1"
                            geometry={nodes.Cube1.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[-0.21, 34.23, 0]}
                        />
                    </group>
                    <group
                        name="Discount"
                        position={[-21.07, -169.97, -54.63]}
                        rotation={[0, 0, 0.26]}
                        scale={0.96}
                    >
                        <group
                            name="Group 26"
                            position={[-3.72, 0, -16.4]}
                            rotation={[0.09, 0, -Math.PI / 9]}
                            scale={1}
                        >
                            <mesh
                                name="%"
                                geometry={nodes["%"].geometry}
                                material={materials["color-2"]}
                                castShadow
                                receiveShadow
                                position={[-27.2, -43.34, 1.56]}
                            />
                            <mesh
                                name="%1"
                                geometry={nodes["%1"].geometry}
                                material={materials["color-2"]}
                                castShadow
                                receiveShadow
                                position={[-27.2, -43.34, 1.56]}
                            />
                            <mesh
                                name="%2"
                                geometry={nodes["%2"].geometry}
                                material={materials["color-2"]}
                                castShadow
                                receiveShadow
                                position={[-27.2, -43.34, 1.56]}
                            />
                            <mesh
                                name="Shape"
                                geometry={nodes.Shape.geometry}
                                material={materials["color-5"]}
                                castShadow
                                receiveShadow
                                position={[-41.29, -75.02, -5.56]}
                            />
                        </group>
                        <group
                            name="Group 25"
                            position={[20.39, -1.29, 10.58]}
                            rotation={[-0.17, -0.02, 0.08]}
                            scale={1}
                        >
                            <mesh
                                name="Ellipse 21"
                                geometry={nodes["Ellipse 21"].geometry}
                                material={materials["color-1"]}
                                castShadow
                                receiveShadow
                                position={[0.86, 58.75, 3.11]}
                            />
                            <mesh
                                name="Ellipse1"
                                geometry={nodes.Ellipse1.geometry}
                                material={materials["color-3"]}
                                castShadow
                                receiveShadow
                                position={[0.86, 58.75, 2.59]}
                            />
                            <mesh
                                name="%3"
                                geometry={nodes["%3"].geometry}
                                material={materials["color-3"]}
                                castShadow
                                receiveShadow
                                position={[-27.2, -43.34, 1.56]}
                            />
                            <mesh
                                name="%4"
                                geometry={nodes["%4"].geometry}
                                material={materials["color-3"]}
                                castShadow
                                receiveShadow
                                position={[-27.2, -43.34, 1.56]}
                            />
                            <mesh
                                name="%5"
                                geometry={nodes["%5"].geometry}
                                material={materials["color-3"]}
                                castShadow
                                receiveShadow
                                position={[-27.2, -43.34, 1.56]}
                            />
                            <mesh
                                name="Shape1"
                                geometry={nodes.Shape1.geometry}
                                material={materials["color-2"]}
                                castShadow
                                receiveShadow
                                position={[-41.29, -75.02, -5.56]}
                            />
                        </group>
                    </group>
                    <group
                        name="speaker"
                        position={[-21.71, 134.65, 120.37]}
                        rotation={[-0.55, 0.74, -0.83]}
                        scale={2.42}
                    >
                        <mesh
                            name="Cube2"
                            geometry={nodes.Cube2.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[38.24, 1.89, -54.33]}
                            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                            scale={1}
                        />
                        <mesh
                            name="Cylinder3"
                            geometry={nodes.Cylinder3.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0.69, 1.65, -56.2]}
                            rotation={[-Math.PI / 2, 0, 0]}
                            scale={1}
                        />
                        <mesh
                            name="Cylinder 22"
                            geometry={nodes["Cylinder 22"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-1.19, -3.22, 15.59]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={1}
                        />
                        <mesh
                            name="Torus1"
                            geometry={nodes.Torus1.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0, 0, 37.58]}
                            scale={0.73}
                        />
                        <mesh
                            name="Cylinder4"
                            geometry={nodes.Cylinder4.geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[0.2, -0.91, -35.39]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={0.73}
                        />
                    </group>
                    <group
                        name="compass"
                        position={[354.93, 276.53, 26.82]}
                        rotation={[0.11, -0.04, -0.39]}
                        scale={1.1}
                    >
                        <mesh
                            name="Cube 21"
                            geometry={nodes["Cube 21"].geometry}
                            material={materials["color-5"]}
                            castShadow
                            receiveShadow
                            position={[-3.29, -21.94, 9.43]}
                            rotation={[0, 0, 2.62]}
                            scale={1}
                        />
                        <mesh
                            name="Cube3"
                            geometry={nodes.Cube3.geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[3.54, -10.06, 9.43]}
                            rotation={[0, 0, -Math.PI / 6]}
                            scale={1}
                        />
                        <mesh
                            name="Rectangle 31"
                            geometry={nodes["Rectangle 31"].geometry}
                            material={materials["Rectangle 31 Material"]}
                            castShadow
                            receiveShadow
                            position={[0.01, -18.08, 1.54]}
                        />
                        <mesh
                            name="Rectangle 21"
                            geometry={nodes["Rectangle 21"].geometry}
                            material={materials["Rectangle 21 Material"]}
                            castShadow
                            receiveShadow
                            position={[0.26, -17.69, 0.1]}
                        />
                        <mesh
                            name="Cylinder 31"
                            geometry={nodes["Cylinder 31"].geometry}
                            material={materials["Cylinder 31 Material"]}
                            castShadow
                            receiveShadow
                            position={[-0.16, 43.33, 0.6]}
                            scale={1}
                        />
                        <mesh
                            name="Cylinder 23"
                            geometry={nodes["Cylinder 23"].geometry}
                            material={materials["Cylinder 23 Material"]}
                            castShadow
                            receiveShadow
                            position={[-0.16, 49.04, 0.6]}
                            scale={1}
                        />
                        <mesh
                            name="Torus2"
                            geometry={nodes.Torus2.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[-0.18, 67.16, 0.53]}
                        />
                        <mesh
                            name="Cylinder5"
                            geometry={nodes.Cylinder5.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0, -19.64, -4.77]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={2.41}
                        />
                    </group>
                    <group
                        name="calculator"
                        position={[434.17, -72.63, 131.85]}
                        rotation={[-Math.PI / 4, 0.19, 0]}
                        scale={0.85}
                    >
                        <mesh
                            name="Rectangle 71"
                            geometry={nodes["Rectangle 71"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[-22.82, 11.7, -3.38]}
                        />
                        <mesh
                            name="Rectangle 81"
                            geometry={nodes["Rectangle 81"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[38.84, 11.7, -3.38]}
                        />
                        <mesh
                            name="Rectangle 61"
                            geometry={nodes["Rectangle 61"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[14.51, 11.7, -3.38]}
                        />
                        <mesh
                            name="Rectangle 51"
                            geometry={nodes["Rectangle 51"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-34.13, -13.45, -3.38]}
                        />
                        <mesh
                            name="Rectangle 41"
                            geometry={nodes["Rectangle 41"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-34.13, -38.07, -3.38]}
                        />
                        <mesh
                            name="Rectangle 32"
                            geometry={nodes["Rectangle 32"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-34.13, -63.96, -3.38]}
                        />
                        <mesh
                            name="Rectangle 22"
                            geometry={nodes["Rectangle 22"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-0.47, 53.94, 8.31]}
                            rotation={[0.7, 0, 0]}
                            scale={[1, 0.85, 1]}
                        />
                        <mesh
                            name="Cube4"
                            geometry={nodes.Cube4.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0, -26.24, -15.03]}
                        />
                    </group>
                    <group
                        name="folder"
                        position={[-171.73, 408.83, -94.5]}
                        rotation={[0.65, 0, 0.34]}
                        scale={0.82}
                    >
                        <mesh
                            name="Rectangle 42"
                            geometry={nodes["Rectangle 42"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[7.43, 7, -5.78]}
                            rotation={[0.26, 0, 0]}
                            scale={1}
                        />
                        <mesh
                            name="Rectangle 33"
                            geometry={nodes["Rectangle 33"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-0.49, 19.27, -11.59]}
                            rotation={[0.17, 0, 0]}
                            scale={1}
                        />
                        <mesh
                            name="Rectangle 23"
                            geometry={nodes["Rectangle 23"].geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[4.02, 21.13, -19.93]}
                            rotation={[0.09, 0, 0]}
                        />
                        <mesh
                            name="Cube5"
                            geometry={nodes.Cube5.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[-0.93, -3.88, -29.72]}
                        />
                    </group>
                    <group
                        name="handle"
                        position={[226.5, -92.65, -248.42]}
                        rotation={[-0.15, -0.57, 0.33]}
                        scale={1.21}
                    >
                        <mesh
                            name="Rectangle 24"
                            geometry={nodes["Rectangle 24"].geometry}
                            material={materials["color-5"]}
                            castShadow
                            receiveShadow
                            position={[3.4, 20.39, 24.57]}
                        />
                        <mesh
                            name="Cylinder 24"
                            geometry={nodes["Cylinder 24"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[62.73, 56.83, 7.86]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={1}
                        />
                        <mesh
                            name="Cylinder6"
                            geometry={nodes.Cylinder6.geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[-59.24, 56.83, 7.86]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={1}
                        />
                        <mesh
                            name="Ellipse 8"
                            geometry={nodes["Ellipse 8"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[64.77, 29.28, 28.54]}
                            rotation={[0, 0, Math.PI / 2]}
                            scale={1}
                        />
                        <mesh
                            name="Ellipse 7"
                            geometry={nodes["Ellipse 7"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[51.91, 16.12, 28.54]}
                            scale={1}
                        />
                        <mesh
                            name="Ellipse 81"
                            geometry={nodes["Ellipse 81"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[38.45, 29.28, 28.54]}
                            rotation={[0, 0, Math.PI / 2]}
                            scale={1}
                        />
                        <mesh
                            name="Ellipse 4"
                            geometry={nodes["Ellipse 4"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[51.91, 42.44, 28.54]}
                            scale={1}
                        />
                        <mesh
                            name="Rectangle 43"
                            geometry={nodes["Rectangle 43"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[-36.57, 29.28, 28.54]}
                            rotation={[0, 0, Math.PI / 2]}
                            scale={1}
                        />
                        <mesh
                            name="Rectangle 34"
                            geometry={nodes["Rectangle 34"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[-48.96, 16.89, 28.54]}
                            scale={1}
                        />
                        <mesh
                            name="Rectangle 44"
                            geometry={nodes["Rectangle 44"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[-61.36, 29.28, 28.54]}
                            rotation={[0, 0, Math.PI / 2]}
                            scale={1}
                        />
                        <mesh
                            name="Rectangle 25"
                            geometry={nodes["Rectangle 25"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[-48.96, 41.68, 28.54]}
                            scale={1}
                        />
                        <mesh
                            name="Ellipse 3"
                            geometry={nodes["Ellipse 3"].geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[51.61, 28.68, 27.46]}
                            scale={1}
                        />
                        <mesh
                            name="Ellipse 22"
                            geometry={nodes["Ellipse 22"].geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[-48.93, 28.68, 27.46]}
                            scale={1}
                        />
                        <mesh
                            name="Ellipse 31"
                            geometry={nodes["Ellipse 31"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[51.61, 28.68, 26.38]}
                            scale={1}
                        />
                        <mesh
                            name="Ellipse2"
                            geometry={nodes.Ellipse2.geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[-48.93, 28.68, 26.38]}
                            scale={1}
                        />
                        <mesh
                            name="Cube6"
                            geometry={nodes.Cube6.geometry}
                            material={materials["color-3"]}
                            castShadow
                            receiveShadow
                            position={[-0.02, 26.93, -4.21]}
                        />
                    </group>
                    <group
                        name="bell"
                        position={[477.86, 102.23, -386.45]}
                        rotation={[0.05, 0.26, -0.17]}
                        scale={1.1}
                    >
                        <mesh
                            name="Torus3"
                            geometry={nodes.Torus3.geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[-0.06, 61.04, -4.11]}
                        />
                        <mesh
                            name="Sphere"
                            geometry={nodes.Sphere.geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[0.51, -55.05, 1.48]}
                            scale={1.22}
                        />
                        <mesh
                            name="Cube7"
                            geometry={nodes.Cube7.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0, 3.4, 0]}
                        />
                    </group>
                    <group
                        name="camera"
                        position={[189.3, 346.84, 53.88]}
                        rotation={[0.45, 0.24, 0.33]}
                        scale={0.83}
                    >
                        <mesh
                            name="Rectangle 35"
                            geometry={nodes["Rectangle 35"].geometry}
                            material={materials["color-1"]}
                            castShadow
                            receiveShadow
                            position={[-0.94, -8.88, -22]}
                            rotation={[Math.PI, 0, 0]}
                        />
                        <mesh
                            name="Rectangle 26"
                            geometry={nodes["Rectangle 26"].geometry}
                            material={materials["color-5"]}
                            castShadow
                            receiveShadow
                            position={[48.37, 20.39, 12.13]}
                        />
                        <mesh
                            name="Ellipse3"
                            geometry={nodes.Ellipse3.geometry}
                            material={materials.lens}
                            castShadow
                            receiveShadow
                            position={[1.5, -9.74, 26.55]}
                        />
                        <mesh
                            name="Cube8"
                            geometry={nodes.Cube8.geometry}
                            material={materials["color-2"]}
                            castShadow
                            receiveShadow
                            position={[0, -8.74, -7.59]}
                        />
                    </group>
                    <OrthographicCamera
                        name="1"
                        makeDefault={true}
                        far={10000}
                        near={-50000}
                    />
                    <hemisphereLight
                        name="Default Ambient Light"
                        intensity={0.75}
                        color="#eaeaea"
                    />
                </scene>
            </group>
        </>
    );
};

export default SplineTestModel;
